### ISSUE TITLE
Problem to run this script

### ISSUE THREAD

**Issue by Giovani93** [gabrielschuck/GS-YEM-Access#1]
Hello.
Here is Marco from Slovakia. I have problem to run this script on My computer, althought everything is set very well and I have newest version of Yamaha expansion manager.
It gives me message, that I have a bad resolution, althought My resolution is set to 1920X1080.
Please, could You look on this script? I have tested exe file, not Autoit script.

**Comment by gabrielschuck** [comment]
@Giovani93
Hi!
This is strange, as it works normally here.
Is the screen orientation not set to "portrait" mode?
If so, the script won't work either, as a resolution would be 1080 X 1920.
Check if this is your case. Leave the screen orientation in "landscape" mode.
If that doesn't work, I'll send you a test script to find out what screen resolution it's returning so we can identify the problem.
Thanks!

**Comment by gabrielschuck** [comment]
Problem desolved. Need to change the text scale size to 100%. Otherwise the script does not identify the screen resolution
